package com.cloudbox.app.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF1976D2)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD1E4FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001D36)
val md_theme_light_secondary = Color(0xFF006C51)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF75F8CC)
val md_theme_light_onSecondaryContainer = Color(0xFF002116)
val md_theme_light_tertiary = Color(0xFF5D52A7)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFE4DFFF)
val md_theme_light_onTertiaryContainer = Color(0xFF190261)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFDFBFF)
val md_theme_light_onBackground = Color(0xFF1A1C1E)
val md_theme_light_surface = Color(0xFFFDFBFF)
val md_theme_light_onSurface = Color(0xFF1A1C1E)

val md_theme_dark_primary = Color(0xFF9ECAFF)
val md_theme_dark_onPrimary = Color(0xFF003258)
val md_theme_dark_primaryContainer = Color(0xFF00497D)
val md_theme_dark_onPrimaryContainer = Color(0xFFD1E4FF)
val md_theme_dark_secondary = Color(0xFF55DBB0)
val md_theme_dark_onSecondary = Color(0xFF003829)
val md_theme_dark_secondaryContainer = Color(0xFF00513C)
val md_theme_dark_onSecondaryContainer = Color(0xFF75F8CC)
val md_theme_dark_tertiary = Color(0xFFC7BFFF)
val md_theme_dark_onTertiary = Color(0xFF2E2176)
val md_theme_dark_tertiaryContainer = Color(0xFF45398D)
val md_theme_dark_onTertiaryContainer = Color(0xFFE4DFFF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1A1C1E)
val md_theme_dark_onBackground = Color(0xFFE2E2E6)
val md_theme_dark_surface = Color(0xFF1A1C1E)
val md_theme_dark_onSurface = Color(0xFFE2E2E6)
